config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'home/index'
  post 'home/search'
  devise_for :users

  resources :vehicles do
    resources :rides do
      resources :requests
    end
  end
  resources :all_requests
  resources :accounts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# HomeController class is responsible for all Home actions.
class HomeController < ApplicationController
  before_action :authenticate_user!
  before_action :check_account

  def index
    @rides = Ride.available_rides
  end

  def show
    @rides = Ride.find(params[:id])
  end

  def search
    @rides = Ride.search(search_params)
    render :index
  end

  private

  def search_params
    params.require(:search).permit(:origin, :destination)
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

# Home helper module.
module HomeHelper
end

app/views/home/index.html.erb
<div class="container">
  <div class="row">
  <div class="heading"><h4>Available Rides</h4>
    </div>
        <%= form_with scope: :search, url: home_search_url, local: true, class: "nifty_form ml-auto" do |request| %>
    <div class="form-row">
      <div class="col">
          <%= request.search_field :origin, class: "form-control", placeholder: "From" %>
      </div>
      <div class="col">
        <%= request.search_field :destination, class: "form-control", placeholder: "Destination" %>
      </div>
      <div class="col">
        <%= request.submit "search", class: "btn btn-search" %>
      </div>
    </div>
  <% end %>
  </div>
  <div>
  <% if @rides.empty? %>
        No rides available.
  <% else %>
      <table class="table rides-table">
        <thead>
        <tr>
          <th scope="col">Ride start time</th>
          <th scope="col">Starting point</th>
          <th scope="col">End point</th>
          <th scope="col">Remaining capacity</th>
          <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        <% @rides.each do |f| %>
          <tr class="ride-rows">
            <th scope="row"><%= f.time.to_formatted_s(:short) %></th>
            <td><%= f.origin %></td>
            <td><%= f.destination %></td>
            <td>
              <%= image_tag 'team.svg' %>
              <span class="badge badge-primary"><%= f.remaining_capacity %></span>
            </td>
             <td class="last-child">
            <% if f.vehicle.user.id == current_user.id %>
            <%= link_to  "cancel", vehicle_ride_path(f.vehicle_id, f.id), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
            <% else %>
            <%= link_to  "request", vehicle_ride_requests_url(f.vehicle_id, f.id), class: "btn btn-secondary" %>
            <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <% end %>

  </div>
</div>