config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'home/index'
  post 'home/search'
  devise_for :users

  resources :vehicles do
    resources :rides do
      resources :requests
    end
  end
  resources :all_requests
  resources :accounts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/controllers/all_requests_controller.rb
# frozen_string_literal: true

class AllRequestsController < ApplicationController
  before_action :authenticate_user!
  def index
    @vehicle_ids = []
    current_user.vehicles.each do |vehicle|
      @vehicle_ids << vehicle.id
    end
    @user_rides = Ride.where(vehicle_id: @vehicle_ids)
    @user_requests = Request.where(user_id: current_user.id)
  end

  def show
    @ride = Ride.find(params[:id])
    @requests = Request.where(ride_id: @ride.id)
  end
end

app/helpers/all_requests_helper.rb
# frozen_string_literal: true

module AllRequestsHelper
end

app/views/all_requests/index.html.erb
<div class="container">
  <div class="row">
  <div class="heading upcoming"><h4>All rides you have requested</h4>
    </div>
  </div>
  <div>
  <% if @user_requests.empty? %>
     You have not requested any rides
  <% else %>
      <table class="table rides-table">
        <thead>
        <tr>
          <th scope="col">Ride start time</th>
          <th scope="col">pickup</th>
          <th scope="col">dropoff</th>
          <th scope="col">vehicle</th>
          <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        <% @user_requests.each do |f| %>
          <tr class="ride-rows">
            <th scope="row"><%= f.ride.time.to_formatted_s(:short) %></th>
            <td><%= f.pickup %></td>
            <td><%= f.dropoff %></td>
            <td>
              <%= f.ride.vehicle.plate %>
            </td>
            <% if f.ride.time > Time.now %>
              <td class="last-child"><%= link_to  "cancel", vehicle_ride_request_url(f.ride.vehicle.id, f.ride.id, f.id), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
              <% end %>
          </tr>
        <% end %>
        </tbody>
      </table>
      <% end %>
  </div>

   <div class="row">
    <div class="heading my-rides"><h4>Rides you have offered</h4>
      </div>
    </div>
    <div>
    <% if @user_rides.empty? %>
    You have not created any rides
    <% else %>
        <table class="table rides-table">
          <thead>
          <tr>
            <th scope="col">Ride start time</th>
            <th scope="col">vehicle plate</th>
            <th scope="col">pickup</th>
            <th scope="col">dropoff</th>
            <th scope="col">Actions</th>
          </tr>
          </thead>
          <tbody>
          <% @user_rides.each do |f| %>
            <tr class="ride-rows">
              <th scope="row"><%= f.time.to_formatted_s(:short) %></th>
              <td><%= f.vehicle.plate %></td>
              <td><%= f.origin %></td>
              <td>
                <%= f.destination %>
              </td>
              <td class="last-child">
              <% if f.time > Time.now %>
                 <%= link_to  "cancel", vehicle_ride_path(f.vehicle_id, f.id), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
              <% end %>

              <%= link_to "ride details", all_request_path(f.id), class: "btn btn-outline-primary" %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
        <% end %>

    </div>
</div>

app/views/all_requests/show.html.erb
<div class="container new">
  <div class="row">
    <div class="heading">
      <h4>Ride details</h4>
    </div>
  </div>

  <div>
    Ride information
    <h6>Time: </h6>
    <p><%= @ride.time.to_formatted_s(:short) %></p>
    <h6>Start point: </h6>
    <p><%= @ride.origin %></p>
    <h6>Destination: </h6>
    <p><%= @ride.destination %></p>

    <hr />
    <h6><b>Requests made</b></h6>
<% if @requests.empty? %>
  No requests have been made to this ride yet.
<% else %>
    <div class="">
      <table class="table table-borderless">
        <thead>
        <tr>
          <th scope="col">first Name</th>
          <th scope="col">Last Name</th>
          <th scope="col">pickup</th>
          <th scope="col">drop off</th>
          <th scope="col">Phone</th>
        </tr>
        </thead>
        <tbody>
        <% @requests.each do |f| %>
          <tr class="ride-rows">
            <td><%= f.user.account.first_name %></td>
            <td><%= f.user.account.last_name %></td>
            <td><%= f.pickup %></td>
            <td> <%= f.dropoff %> </td>
            <td><%= f.user.account.phone_number %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <% end %>

  </div>
  </div>

</div>