config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'home/index'
  post 'home/search'
  devise_for :users

  resources :vehicles do
    resources :rides do
      resources :requests
    end
  end
  resources :all_requests
  resources :accounts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/models/vehicle.rb
# frozen_string_literal: true

# Vehicle model.
# Responsible for all the vehicle model validations and model functions
class Vehicle < ApplicationRecord
  validates :plate, :capacity, :make, :colour, presence: true
  validates :plate, length: {
    minimum: 6,
    maximum: 8
  }, uniqueness: true

  has_many :rides, dependent: :destroy
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
end

app/controllers/vehicles_controller.rb
# frozen_string_literal: true

class VehiclesController < ApplicationController
  before_action :authenticate_user!
  before_action :fetch_vehicle, only: %i[update edit destroy]

  def index
    @vehicles = current_user.vehicles
  end

  def new
    @vehicle = Vehicle.new
  end

  def show; end

  def create
    vehicle = current_user.vehicles.build(vehicle_params)
    if vehicle.save
      flash[:notice] = 'vehicles added!'
      redirect_to action: 'index'
    else
      flash[:error] = vehicle.errors.messages
      render :new
    end
  end

  def update
    if @vehicle.update_attributes(vehicle_params)
      flash[:notice] = 'vehicles updated!'
    else
      flash[:error] = 'Failed to edit vehicles!'
    end
    redirect_to action: 'index'
  end

  def edit; end

  def destroy
    if @vehicle.destroy
      flash[:notice] = 'Vehicle deleted!'
    else
      flash[:error] = 'Failed to delete this vehicles!'
    end
    redirect_to action: 'index'
  end

  private

  def fetch_vehicle
    @vehicle = Vehicle.find(params[:id])
  end

  # we used strong parameters for the validation of params
  def vehicle_params
    params.require(:vehicle).permit(:make, :colour, :plate, :capacity)
  end
end

app/helpers/vehicles_helper.rb
# frozen_string_literal: true

module VehiclesHelper
end

app/views/vehicles/edit.html.erb
  <div class="container edit">
    <div class="row">
      <div class="heading">
        <h4>Edit registration</h4>
      </div>
    </div>
    <div class="car-reg-form">
      <%= form_with scope: :vehicle, url: vehicle_path, method: :put , local: true, class: "nifty_form" do |vehicle| %>
        <div class="form-group">
          <%= vehicle.label :make %><br />
            <%= vehicle.text_field :make, class: "form-control", placeholder: "Toyota vitz" %>
        </div>
        <div class="form-group">
          <%= vehicle.label :colour %><br />
            <%= vehicle.text_field :colour, class: "form-control", placeholder: "blue" %>
        </div>
        <div class="form-group">
          <%= vehicle.label :plate %><br />
            <%= vehicle.text_field :plate, class: "form-control", placeholder: "KBZ 001S" %>
              <% if flash[:error] %>
                <p class="error"> Plate
                  <%= flash[:error][:plate][0] %>
                </p>
                <% end %>
        </div>
        <div class="form-group">
          <%= vehicle.label :capacity %><br />
            <%= vehicle.text_field :capacity, class: "form-control", placeholder: "4" %>
        </div>
        <div class="form-group">
          <%= vehicle.submit "Register vehicle", class: "btn btn-success" %>
        </div>
        <% end %>
    </div>

  </div>

app/views/vehicles/index.html.erb
<div class="container index">
  <div class="row">
    <div class="heading">
      <h4>Registered vehicles</h4>
    </div>
    <%= link_to 'Add vehicle', new_vehicle_path, class: "btn btn-outline-success ml-auto" %>
  </div>

  <div class="vehicle-list">
   <% if @vehicles.empty? %>
          No Vehicles added yet. Please add a vehicle.
    <% else %>
  <table class="table vehicles table-borderless">
    <thead>
    <tr>
      <th scope="col">Number plate</th>
      <th scope="col">Make/Model</th>
      <th scope="col">Colour</th>
      <th scope="col">Capacity</th>
      <th scope="col">Actions</th>
    </tr>
    </thead>
    <tbody>
    <% @vehicles.each do |f| %>
      <tr class="ride-rows">
        <th scope="row"><%= f.plate %></th>
        <td><%= f.make %></td>
        <td><%= f.colour %></td>
        <td><%= f.capacity %></td>
        <td class="last-child">
          <%=link_to  image_tag('plus.svg'), vehicle_rides_url(f.id) %>
          <%=link_to  image_tag('trash.svg'), vehicle_path(f), method: :delete, data: { confirm: 'Are you sure?' } %>
          <%=link_to  image_tag('writing.svg'), edit_vehicle_path(f.id) %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <% end %>
  </div>
</div>

app/views/vehicles/new.html.erb
<div class="container new">
  <div class="row">
    <div class="heading">
      <h4>New Vehicle registration</h4>
    </div>
  </div>
  <div class="car-reg-form">
    <%= form_with scope: :vehicle, url: vehicles_path, local: true, class: "nifty_form" do |vehicle| %>
      <div class="form-group">
        <%= vehicle.label :make %><br />
        <%= vehicle.text_field :make, class: "form-control", placeholder: "Toyota vitz" %>
      </div>
      <div class="form-group">
        <%= vehicle.label :colour %><br />
        <%= vehicle.text_field :colour, class: "form-control", placeholder: "blue" %>
      </div>
      <div class="form-group">
        <%= vehicle.label :plate %><br />
        <%= vehicle.text_field :plate, class: "form-control", placeholder: "KBZ 001S" %>
        <% if flash[:error] %>
          <p class="error"> Plate <%= flash[:error][:plate][0] %> </p>
        <% end %>
      </div>
      <div class="form-group">
        <%= vehicle.label :capacity %><br />
        <%= vehicle.text_field :capacity, class: "form-control", placeholder: "4" %>
      </div>
      <div class="form-group">
        <%= vehicle.submit "Register vehicle", class: "btn btn-success" %>
      </div>
    <% end %>
  </div>

</div>