config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'home/index'
  post 'home/search'
  devise_for :users

  resources :vehicles do
    resources :rides do
      resources :requests
    end
  end
  resources :all_requests
  resources :accounts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/models/ride.rb
# frozen_string_literal: true

class Ride < ApplicationRecord
  belongs_to :vehicle
  has_many :requests, dependent: :destroy
  validates :time, :remaining_capacity, :origin, :destination, presence: true

  scope(:available_rides, lambda do
    where('time > ?', Time.now).where('remaining_capacity >?', 0)
  end)

  scope(:search, lambda do |name|
    @rides = where('lower(origin) like lower(?) OR lower(destination) like lower(?)',
                   name[:origin], name[:destination])
  end)
end

app/controllers/rides_controller.rb
# frozen_string_literal: true

# Ride controller class
# This is the controller responsible on all Ride actions.
class RidesController < ApplicationController
  before_action :authenticate_user!
  before_action :fetch_ride, only: %i[show update destroy]

  def index
    @vehicle_id = params[:vehicle_id]
    @rides = Ride.where(vehicle_id: @vehicle_id)
  end

  def new
    @ride = Ride.new
  end

  def show; end

  def edit; end

  def create
    @vehicle = Vehicle.find(params[:vehicle_id])
    @ride = @vehicle.rides.build(ride_params)
    if @ride.save!
      flash[:notice] = 'ride added!'
    else
      flash[:alert] = @ride.errors.messages
    end
    redirect_to action: 'index'
  end

  def update
    if @ride.update_attributes(ride_params)
      flash[:notice] = 'ride updated!'
      redirect_to action: 'index'
    else
      flash[:alert] = 'Failed to edit ride!'
      render :edit
    end
  end

  def destroy
    requests = @ride.requests
    if @ride.destroy
      flash[:notice] = 'Ride canceled!'
      requests.each do |request|
        notify_requester(request.user.account.phone_number)
      end
    else
      flash[:alert] = 'Failed to delete this vehicles!'
    end
    redirect_to action: 'index'
  end

  private

  def fetch_ride
    @ride = Ride.find(params[:id])
  end

  def ride_params
    params.require(:ride).permit(:time, :remaining_capacity, :destination, :origin)
  end

  def notify_requester(number)
    nexmo = Nexmo::Client.new
    nexmo.sms.send(
      from: 'Carpooling App',
      to: number,
      text: 'Your ride has been canceled please visit carpooling app to book another.'
    )
  end
end

app/helpers/rides_helper.rb
# frozen_string_literal: true

module RidesHelper
end

app/views/rides/edit.html.erb
<div class="container">
<div class="row">
  <div class="heading">
    <h4>Edit ride</h4>
  </div>
</div>
<div class="car-reg-form">
<%= form_with scope: :ride, url: vehicle_ride_path,  method: :put , local: true, class: "nifty_form" do |request| %>
  <div class="form-group">
    <%= request.label :time %><br />
    <%= request.datetime_local_field :time, class: "form-control", placeholder: "departure time" %>
  </div>

  <div class="form-group">
    <%= request.label :remaining_capacity %><br />
    <%= request.text_field :remaining_capacity, class: "form-control", placeholder: "1" %>
  </div>
  <div class="form-group">
    <%= request.label :origin %><br />
    <%= request.text_field :origin, class: "form-control", placeholder: "start point" %>
  </div>
  <div class="form-group">
    <%= request.label :destination %><br />
    <%= request.text_field :destination, class: "form-control", placeholder: "destination" %>
  </div>
  <%= request.submit "Update ride", class: "btn btn-success" %>
<% end %>
</div>
</div>

app/views/rides/index.html.erb
<div class="container">
  <div class="row">
    <div class="heading"><h4>Rides page</h4>
  </div>
  <%= link_to  "create new ride", vehicle_rides_path, { class: "btn btn-outline-success ml-auto" , "data-toggle" => "modal", "data-target" => "#exampleModalCenter"}   %>
  </div>
 <% if @rides.empty? %>
        You have no rides for this vehicle yet.
  <% else %>
  <table class="table rides table-borderless">
    <thead>
    <tr>
      <th scope="col">Time</th>
      <th scope="col">remaining capacity</th>
      <th scope="col">From</th>
      <th scope="col">Destination</th>
      <th scope="col">Actions</th>
    </tr>
    </thead>
    <tbody>
    <% @rides.each do |f| %>
      <tr class="ride-rows">
        <th scope="row"><%= f.time.to_formatted_s(:short) %></th>
        <td><%= f.remaining_capacity %></td>
        <td><%= f.origin %></td>
        <td><%= f.destination %></td>
        <td class="last-child">
          <%=link_to  image_tag('trash.svg'), vehicle_ride_path(f.vehicle.id, f.id), method: :delete, data: { confirm: 'Are you sure?' } %>
          <%=link_to  image_tag('writing.svg'), edit_vehicle_ride_path(f.vehicle.id, f.id) %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <% end %>

  </div>

<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-body">
          <%= form_with scope: :ride, url: vehicle_rides_path, local: true, class: "nifty_form" do |request| %>
          <div class="form-group">
            <%= request.label :time %><br />
            <%= request.datetime_local_field :time, class: "form-control", placeholder: "departure time" %>
          </div>
          <%= request.hidden_field :vehicle_id, value: @vehicle_id %>
          <div class="form-group">
            <%= request.label :remaining_capacity %><br />
            <%= request.text_field :remaining_capacity, class: "form-control", placeholder: "1" %>
          </div>
          <div class="form-group">
            <%= request.label :origin %><br />
            <%= request.text_field :origin, class: "form-control", placeholder: "start point" %>
          </div>
        <div class="form-group">
            <%= request.label :destination %><br />
            <%= request.text_field :destination, class: "form-control", placeholder: "destination" %>
        </div>
              <%= request.submit "create new ride", class: "btn btn-success" %>
            <% end %>
      </div>
    </div>
  </div>
</div>